DIMO-Network/dimo-login

.gitignore, src/App.tsx, src/components/Auth/EmailInput.tsx, src/components/Auth/OtpInput.tsx, src/context/AuthContext.tsx, src/services/accountsService.ts, src/utils/authUtils.ts
- Hooks up API requests for sending OTP, and verifying
- Handles flow to go from entering email -> entering OTP -> getting mocked token 
Note
- Doesn't deal with the case where user does not currently have an account to push them down account creation flow
https://www.loom.com/share/e3cddcabcc2745ceb3297b926f4e9dcc?from_recorder=1&focus_title=1
=> OTP Integration for Login

src/components/Auth/OtpInput.tsx, src/components/Auth/SuccessPage.tsx, src/context/AuthContext.tsx, src/models/user.ts, src/services/accountsService.ts
- Adds request to get user detail, and make the user object a part of global state
- Extends the authenticate user function to include a call to get the user details
- Updates success page to showcase the user's wallet address that has been fetched
=> Fetching User Support

src/App.tsx, src/components/Shared/Loader.tsx, src/context/AuthContext.tsx, src/context/DevCredentialsContext.tsx, src/index.tsx, src/services/accountsService.ts, src/utils/authUtils.ts
Uses message passing between app and SDK to pass credentials (client ID, redirectUri, apiKey)
=> Fetch Dev Creds using Message Passing

src/App.tsx, src/components/Auth/EmailInput.tsx, src/components/Auth/OtpInput.tsx, src/components/Vehicles/VehicleCard.tsx, src/components/Vehicles/VehicleManager.tsx, src/context/AuthContext.tsx, src/context/DevCredentialsContext.tsx, src/models/vehicle.ts, src/services/identityService.ts, src/services/permissionsService.ts, src/services/turnkeyService.ts, src/utils/authUtils.ts
Architectural Changes
- JWT and Auth Step made Globally Accessible and added to the Auth Context
- The Authenticate User function is now responsible for setting the JWT, and moving to the next step
Functional additions
- Fetching and displaying Vehicles
- Sharing Vehicles
https://www.loom.com/share/4c0bb8bfb851470eb71364e2c007e06b
=> Sign/Share Permissions Functionality

src/components/Shared/Loader.tsx, src/context/AuthContext.tsx
- Sets loading messages dynamically
=> Better Loading Messages

src/components/Auth/EmailInput.tsx, src/components/Auth/OtpInput.tsx, src/components/Shared/Loader.tsx, src/components/Vehicles/VehicleManager.tsx, src/context/AuthContext.tsx, src/models/resultTypes.ts, src/services/accountsService.ts, src/services/turnkeyService.ts, src/utils/authUtils.ts
- Remove use of the bang operator, and be explicit with null types
- Define result types
=> Cleanup Types

src/App.tsx, src/context/DevCredentialsContext.tsx, src/services/identityService.ts
=> Dev Licence Check

src/components/Vehicles/VehicleManager.tsx, src/services/turnkeyService.ts
=> Bulk Set Permissions

src/App.tsx, src/components/Vehicles/VehicleManager.tsx, src/context/DevCredentialsContext.tsx, src/services/identityService.ts
=> Configurable Vehicles

src/components/Auth/EmailInput.tsx, src/components/Auth/OtpInput.tsx, src/components/Shared/ErrorMessage.tsx, src/components/Shared/Header.tsx, src/components/Shared/LoadingScreen.tsx, src/components/Vehicles/VehicleManager.tsx
=> Responsive Screens

src/App.tsx, src/components/Auth/EmailInput.tsx, src/services/accountsService.ts, src/services/identityService.ts, src/services/sessionService.ts, src/services/storageService.ts, src/services/turnkeyService.ts, src/utils/authUtils.ts
Persistence scoped to client ID's
https://www.loom.com/share/0419fbf508f946ada029ca887198a00e
Note: Doesn't handle SDK interaction yet
=> Scoped Persistence

src/components/Vehicles/VehicleCard.tsx
https://www.loom.com/share/1b933f9a0c3e46b494a9a7219e72e1a0?from_recorder=1&focus_title=1
=> Fix Select on Vehicles

package-lock.json, package.json, src/components/Vehicles/VehicleManager.tsx, src/services/identityService.ts, src/services/turnkeyService.ts, src/utils/authUtils.ts
This push is just to test if the assets dimo xyz ipfs call works from a dimo.org domain
=> Updated Transactions SDK, Wallet Session + SACD Permissions

src/App.tsx, src/components/Auth/EmailInput.tsx, src/components/Auth/OtpInput.tsx, src/components/Vehicles/VehicleManager.tsx, src/context/AuthContext.tsx, src/context/DevCredentialsContext.tsx, src/services/sessionService.ts, src/utils/authUtils.ts
- Parse an entry state passed from the SDK
- Deprecate authStep, for UI State
SDK Dependency
- For older versions of the SDK, entry state will always be EMAIL_INPUT
=> Integrate with Decoupled SDK State

src/components/Auth/SuccessPage.tsx
https://www.loom.com/share/739853d5ce4d4cf7acf871cce40b9ab7
=> continue button on success

src/components/Vehicles/VehicleManager.tsx, src/services/turnkeyService.ts
No active client on new popup, requires reinitializing
=> initialize if not active client

src/App.tsx, src/components/AdvancedTransaction/AdvancedTransaction.tsx, src/components/Shared/Card.tsx
=> UI Cleanup

src/components/Auth/EmailInput.tsx, src/components/Auth/SuccessPage.tsx, src/components/Vehicles/VehicleManager.tsx, src/context/DevCredentialsContext.tsx, src/services/storageService.ts, src/utils/authUtils.ts
- Checkbox to grant email permission
- Send full auth payload to SDK
=> Expose Wallet Data

src/components/Vehicles/VehicleManager.tsx, src/context/AuthContext.tsx, src/utils/authUtils.ts, src/utils/errorUtils.ts, src/utils/messageHandler.ts, src/utils/txnUtils.ts
- Permission Skipping Logic moved to Vehicle Manager
- Message sending generalized, and cleaned up
=> Permissions Toggle Cleanup

src/components/Auth/EmailInput.tsx, src/components/Auth/OtpInput.tsx, src/components/Vehicles/VehicleCard.tsx, src/components/Vehicles/VehicleManager.tsx, src/context/DevCredentialsContext.tsx, src/services/identityService.ts, src/services/permissionsService.ts
- Enter should trigger next step (For Otp, and Email - we’ll leave it for transaction and sharing since those have multiple options)
- Fix hovers on vehicles/checkbox
- Clicking on the label
- Get Dev License Alias, and render on
- Permission Template
- Email Entry
=> UI Cleanup | Dec 3rd

src/components/Auth/SuccessPage.tsx, src/services/accountsService.ts, src/services/turnkeyService.ts, src/utils/authUtils.ts, src/utils/cryptoUtils.ts
Logout Functionality
- Helper function created to remove cookie/user data from storage
Cleanup
- Crypto Utils, moved to their own file
Demo: https://www.loom.com/share/9c41ed83b9534876ba72246c9a3e8962
=> Logout Functionality + Code Cleanup

src/App.tsx, src/components/AdvancedTransaction/AdvancedTransaction.tsx, src/components/AdvancedTransaction/CancelledTransaction.tsx, src/components/AdvancedTransaction/SuccessfulTransaction.tsx, src/utils/errorUtils.ts, src/utils/txnUtils.ts
Popup/Redirect
- Sends txn hash, and then moves to a successful txn screen
Embed
- Sends txn hash, and stays on successful txn screen
=> Txn Approve/Cancel States

src/components/Vehicles/VehicleManager.tsx, src/services/permissionsService.ts
Adds a permission template, that doesn't have "COMMANDS"
=> support separate permission templates

src/App.tsx, src/components/AdvancedTransaction/AdvancedTransaction.tsx, src/components/AdvancedTransaction/SuccessfulTransaction.tsx, src/components/Auth/EmailInput.tsx, src/components/Auth/OtpInput.tsx, src/components/Auth/SuccessPage.tsx, src/components/Vehicles/SuccessfulPermissions.tsx, src/components/Vehicles/VehicleCard.tsx, src/components/Vehicles/VehicleManager.tsx, src/context/AuthContext.tsx, src/context/DevCredentialsContext.tsx, src/context/UIManagerContext.tsx, src/utils/authUtils.ts, src/utils/messageHandler.ts, src/utils/txnUtils.ts
Introduces a Success Screen for vehicles shared, where users can see the vehicles that were successfully shared
Manages navigation states
- If user clicks success, or cancel, approve/reject, back buttons for all modes (redirect, embed, popup)
=> Handlers for Success/Cancellation Screens

package-lock.json, package.json, src/components/AdvancedTransaction/AdvancedTransaction.tsx, src/components/Vehicles/VehicleManager.tsx, src/services/permissionsService.ts, src/services/turnkeyService.ts
- Use new types + methods from transactions SDK
- Abstract logic to different services
=> Transaction SDK Update + Permissions Rendering

src/App.tsx, src/components/AdvancedTransaction/AdvancedTransaction.tsx, src/components/Auth/EmailInput.tsx, src/components/Auth/OtpInput.tsx, src/components/Shared/Loader.tsx, src/components/Vehicles/VehicleManager.tsx, src/context/AuthContext.tsx, src/context/DevCredentialsContext.tsx, src/context/UIManagerContext.tsx, sucess-page/index.html
All messages and states handled by the UIManager now, instead of auth context/dev credentials context
=> Loading and Error Management

src/components/AdvancedTransaction/AdvancedTransaction.tsx, src/components/Vehicles/VehicleManager.tsx, src/services/permissionsService.ts, src/utils/dateUtils.ts
Support for Expiration Dates to be provided by developer
=> Expiration Date Support

src/App.tsx, src/components/AdvancedTransaction/AdvancedTransaction.tsx, src/components/AdvancedTransaction/SuccessfulTransaction.tsx, src/components/Auth/SuccessPage.tsx, src/components/Vehicles/SuccessfulPermissions.tsx, src/components/Vehicles/VehicleManager.tsx, src/context/AuthContext.tsx, src/context/DevCredentialsContext.tsx, src/models/user.ts, src/services/accountsService.ts, src/services/identityService.ts, src/services/sessionService.ts, src/services/turnkeyService.ts, src/utils/authUtils.ts
- Session Initialization State
- Default Types
- Removal of the "non-null" operator, and casting types
=> Code Cleanup

README.md, src/components/Auth/EmailInput.tsx, src/components/Auth/OtpInput.tsx, src/components/Vehicles/VehicleCard.tsx, src/components/Vehicles/VehicleManager.tsx, src/context/AuthContext.tsx, src/models/account.ts, src/models/permissions.ts, src/models/user.ts, src/models/web3.ts, src/services/accountsService.ts, src/services/authService.ts, src/services/permissionsService.ts, src/services/turnkeyService.ts, src/utils/authUtils.ts
- Switch to object types for functions taking more than 3 params
- Remove unused
- Declare types
- Add conventions used in README
=> Params Cleanup

src/components/Shared/Loader.tsx
---
- fixed spacing for loading screen
---
[ACC-208](https://linear.app/dimo/issue/ACC-208/[liwd]-ux-fix-on-auth-loading-animation)
=> UX fix on auth loading animation

src/components/Vehicles/SuccessfulPermissions.tsx, src/components/Vehicles/VehicleManager.tsx, src/models/vehicle.ts, src/services/identityService.ts
https://www.loom.com/share/eff0c460011f496cb0660d473c352fbe?from_recorder=1&focus_title=1
=> Pagination on Vehicles

src/App.tsx, src/components/Vehicles/SelectVehicles.tsx, src/components/Vehicles/SuccessfulPermissions.tsx, src/components/Vehicles/VehicleCard.tsx, src/components/Vehicles/VehicleManager.tsx, src/models/vehicle.ts, src/services/identityService.ts
=> Compatible/Incompatible, Pre-Select Screen, Select All Support

src/App.tsx, src/components/Vehicles/ManageVehicle.tsx, src/components/Vehicles/SelectVehicles.tsx, src/components/Vehicles/SuccessfulPermissions.tsx, src/components/Vehicles/VehicleCard.tsx, src/components/Vehicles/VehicleManager.tsx, src/models/vehicle.ts, src/services/identityService.ts, src/utils/dateUtils.ts
https://www.loom.com/share/e80fe3bb95704727ac43e99e1bb2f463
=> Acc 153 liwd implement designs to revokeextend vehicle permissions

src/components/Vehicles/SuccessfulPermissions.tsx
=> add revoked vehicles on redirect

src/components/Vehicles/ManageVehicle.tsx, src/components/Vehicles/SuccessfulPermissions.tsx, src/utils/authUtils.ts, src/utils/dateUtils.ts, src/utils/errorUtils.ts, src/utils/messageHandler.ts, src/utils/txnUtils.ts
https://www.loom.com/share/c0d976a1489d40ceaf9205cd720855b2
=> Extend Support + Logout Indication on Redirect

src/components/Auth/EmailInput.tsx, src/components/Shared/Checkbox.tsx
---
As described in [the section 3 of the Figma file](https://www.figma.com/design/oMYga1BOIZzDRuGBVTlK20/Web-Login-UX-DIMO-Org-Fork?node-id=3131-1009&t=uwqEaoYQKUUjtA7I-1), the checkmark component should be as designed.
---
=> Checkmark component should be rounded check icon

src/components/Vehicles/SelectVehicles.tsx, src/components/Vehicles/VehicleManager.tsx, src/utils/dateUtils.ts
=> Acc 253 liwd loosen expirationdate default to 10 years instead of 1

src/components/Auth/OtpInput.tsx
=> fix slipping

package-lock.json, package.json, src/components/Vehicles/EmptyState.tsx, src/components/Vehicles/SelectVehicles.tsx
---
- Added Apple store button inside the empty state
- Added Google store button inside the empty state
---
=> [LIWD] Add Apple & Google store buttons inside the empty state

src/components/Auth/EmailInput.tsx
=> responsive  SSO buttons

src/App.tsx, src/components/Shared/ErrorScreen.tsx, src/components/Shared/LoadingScreen.tsx, src/index.css
=> responsive tablet screebs

src/App.tsx, src/components/Auth/EmailInput.tsx, src/components/Shared/ErrorScreen.tsx, src/components/Shared/LoadingScreen.tsx, src/index.css
Essentially makes padding/background color styles only applied with a min height in addition to min width
=> Development -> Main

src/components/AdvancedTransaction/AdvancedTransaction.tsx, src/components/AdvancedTransaction/SuccessfulTransaction.tsx, src/components/Auth/EmailInput.tsx, src/components/Auth/SuccessPage.tsx, src/components/Vehicles/SelectVehicles.tsx, src/components/Vehicles/SuccessfulPermissions.tsx, src/context/AuthContext.tsx, src/context/DevCredentialsContext.tsx, src/services/identityService.ts, src/types/Credential.ts, src/types/index.ts, src/utils/authUtils.ts, src/utils/errorUtils.ts, src/utils/messageHandler.ts, src/utils/urlHelpers.ts
---
- add: support to handle utm params
- refactor: improve uri validation on allowed uris by the contract
=> [LIWD] Support custom UTM via URL parameters

src/components/Auth/EmailInput.tsx, src/components/Shared/Checkbox.tsx
---
- Clicking the share email text toggles the checkbox
---
https://github.com/user-attachments/assets/f29e5928-6f5e-471b-a181-2c98573f3970
=> [LIWD] Make email text clickable and toggles capture email checkbox

src/services/turnkeyService.ts
Sets dimo.org as rpid for both
Uses preview authenticator name
=> Use Authenticator Name

src/components/Shared/ConnectCarButton.tsx, src/components/Vehicles/VehicleManager.tsx, src/context/OraclesContext.tsx, src/index.tsx, src/utils/authUrls.ts
- Creates an oracles context, which can deal with the value of the onboarding param setup by developers
=> Onboarding Param

src/components/Connections/ConnectTesla.tsx, src/components/Shared/ConnectCarButton.tsx, src/components/Vehicles/AddVehicle.tsx, src/components/Vehicles/CompatibilityCheck.tsx, src/components/Vehicles/MintVehicle.tsx, src/components/Vehicles/SelectVehicles.tsx
- Connect Vehicle Button
- Oracles global context
- Parsing message from SDK
=> v0.0.20: Onboarding/Oracles Support #63

src/components/Shared/AutoCompleteInput.tsx, src/components/Vehicles/AddVehicle.tsx, src/components/Vehicles/CompatibilityCheck.tsx, src/utils/tablelandUtils.ts
- Autocomplete Support
- Tableland instead of Device Definitions
- Spacing Fixes
=> April 1st: UI Fixes

src/components/Auth/EmailInput.tsx, src/context/DevCredentialsContext.tsx, src/context/UIManagerContext.tsx, src/enums/config.ts, src/enums/index.ts, src/utils/authUrls.ts, src/utils/uiUtils.ts
=> Updated Multiple Login Modes

src/components/Vehicles/VehicleManager.tsx, src/enums/config.ts, src/models/permissions.ts, src/services/permissionsService.ts
---
- Add region support and contract attachment links in permissions handling
---
=> DEMO: Contract attachment

src/components/Shared/AutoCompleteInput.tsx, src/components/Shared/Input.tsx, src/components/Shared/PermissionsStep.tsx, src/components/Shared/VirtualKeyStep.tsx
---
- changed text on vehicle steps
- fix font between input and select components
---
=> fix: UI fixes on add vehicle page

src/context/DevCredentialsContext.tsx
---
- Refactored DevContex for readability
=> Refactor Dev Context

src/services/storageService.ts
---
- Improved logic to store cookies
- Removed redundant comments
=> refactor: improved logic to store cookies

src/App.tsx, src/components/AdvancedTransaction/AdvancedTransaction.tsx, src/components/AdvancedTransaction/CancelledTransaction.tsx, src/components/AdvancedTransaction/SuccessfulTransaction.tsx, src/components/Auth/EmailInput.tsx, src/components/Auth/Logout.tsx, src/components/Auth/OtpInput.tsx, src/components/Auth/PasskeyGeneration.tsx, src/components/Auth/SuccessPage.tsx, src/components/Connections/ConnectDevice.tsx, src/components/Connections/ConnectSmartcar.tsx, src/components/Connections/ConnectTesla.tsx, src/components/Shared/ErrorScreen.tsx, src/components/Shared/LoadingScreen.tsx, src/components/Vehicles/AddVehicle.tsx, src/components/Vehicles/EmptyState.tsx, src/components/Vehicles/ManageVehicle.tsx, src/components/Vehicles/MintVehicle.tsx, src/components/Vehicles/SelectVehicles.tsx, src/components/Vehicles/SuccessfulPermissions.tsx, src/components/Vehicles/VehicleManager.tsx
=> fix: responsive design

src/App.tsx, src/components/AdvancedTransaction/AdvancedTransaction.tsx, src/components/AdvancedTransaction/SuccessfulTransaction.tsx, src/components/Shared/ErrorScreen.tsx, src/context/DevCredentialsContext.tsx, src/hooks/useErrorHandler.ts, src/services/identityService.ts, src/validations/advancedTransactionValidations.ts, src/validations/globalValidations.ts, src/validations/index.ts, src/validations/vehicleManagerValidations.ts
---
- implemented centralized validation system with error handling
---
**Advanced transaction w/o transaction data**
**Vehicle manager w/o template permission id**
**Invalid credentials**
**Missing Redirect URI**
**Missing client ID**
=> feat: validation system

src/context/DevCredentialsContext.tsx
---
- removed standalone check when applying dev credentials config
=> fix: login with state parameters for pop up 

src/context/DevCredentialsContext.tsx
---
- extract auth initialization logic into separate async function
=> fix: social login for pop up

src/services/storageService.ts
=> Reduce cookie expiration from 10 years to 2 week

src/components/AdvancedTransaction/AdvancedTransaction.tsx, src/components/Auth/CachedEmail.tsx, src/components/Auth/EmailInput.tsx, src/components/Auth/Logout.tsx, src/components/Auth/OtpInput.tsx, src/components/Auth/PasskeyGeneration.tsx, src/components/Auth/PasskeyLogin.tsx, src/components/Shared/Loader.tsx, src/components/Shared/LoadingContent.tsx, src/components/Shared/PollingVirtualKeyStep.tsx, src/components/Shared/PrimaryButton.tsx, src/components/Vehicles/CompatibilityCheck.tsx, src/components/Vehicles/ManageVehicle.tsx, src/components/Vehicles/MintVehicle.tsx, src/components/Vehicles/SelectVehicles.tsx, src/context/AuthContext.tsx, src/hooks/useAuthenticateUserWithUI.tsx, src/models/resultTypes.ts, src/services/accountsService.ts, src/services/storageService.ts, src/services/turnkeyService.ts, src/utils/authUtils.ts
=> Development --> Main

package-lock.json, package.json
---
- update @turnkey/http dependency to version 2.22.0
=> chore: turnkey http version

src/context/DevCredentialsContext.tsx
---
- Fixed entry state for validation system in pop up mode
=> fix: entry state for validations

package-lock.json, package.json
---
- fixed empty state, go back to version 1.2.18
=> fix: empty state

src/context/DevCredentialsContext.tsx
---
- fixed loading when waiting params for pop mode
=> fix: loading when waiting params for pop mode

src/context/DevCredentialsContext.tsx
---
- Added validation to avoid waiting for credentials when client_id is missing for redirect mode
=> feature: improved validation for popup mode
